name             'vim'
maintainer       'Sous Chefs'
maintainer_email 'help@sous-chefs.org'
license          'Apache-2.0'
description      'Installs vim and optional extra packages.'
source_url       'https://github.com/chef-cookbooks/vim'
issues_url       'https://github.com/chef-cookbooks/vim/issues'
chef_version     '>= 15.3'

version '3.0.3'

supports 'debian'
supports 'ubuntu'
supports 'redhat'
supports 'centos'
supports 'fedora'
supports 'scientific'
supports 'oracle'
supports 'amazon'
supports 'zlinux'
supports 'suse'
supports 'opensuse'
supports 'opensuseleap'
